### ISSUE TITLE
Extend exceptions_punctuation fixer

### ISSUE THREAD

**Issue by juliangut** [PedroTroller/PhpCSFixer-Custom-Fixers#138]
There are situation in which exception messages come from variables or other function returns, such as *printf

```
// Option 1

// wrong
throw new \InvalidArgumentException(\sprintf('Invalid algorithm "%s"', $algo));

// good
throw new \InvalidArgumentException(\sprintf('Invalid algorithm "%s".', $algo));

// Option 2

// wrong
throw new \InvalidArgumentException($$message = $this->formatException($exception)); // Invalid algorithm "xx"

// good
throw new \InvalidArgumentException($$this->formatException($exception)); // Invalid algorithm "xx".
```

Is it possible to extend this fixer to support this cases? Option 2 may be difficult, but maybe option 1 is feasable

**Comment by PedroTroller** [comment]
Hello @juliangut.

The first usecase is already implemented : https://github.com/PedroTroller/PhpCSFixer-Custom-Fixers#fixes-3

For the second one, it is not possible to implement it with a tool like php-cs-fixer because this tool is only fixing errors/cases based on syntax and not on logic... Maybe somthing like https://github.com/rectorphp/rector can do it.

**Comment by PedroTroller** [comment]
If you have other questions about this topic, don't hesitate to re-open this issue :wink:
